name = "motlin-chess"
compatibility_date = "2025-01-12"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[vars]
ENVIRONMENT = "development"

[env.production.vars]
ENVIRONMENT = "production"
